# Generated for vpn_v2ray_sales_bot v0.1.0
from decimal import Decimal
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('title', models.CharField(default='فروشگاه VPN', max_length=120, verbose_name='عنوان ربات/فروشگاه')),
                ('telegram_bot_token', models.CharField(blank=True, max_length=255, verbose_name='توکن ربات تلگرام')),
                ('support_chat_id', models.CharField(blank=True, max_length=64, verbose_name='چت آیدی پشتیبانی')),
                ('admin_chat_id', models.CharField(blank=True, max_length=64, verbose_name='چت آیدی مدیر برای اعلان‌ها')),
                ('dollar_rate_toman', models.DecimalField(decimal_places=0, default=Decimal('60000'), max_digits=18, verbose_name='قیمت هر دلار به تومان')),
                ('oxapay_merchant_api_key', models.CharField(blank=True, max_length=255, verbose_name='Merchant API Key درگاه OxaPay')),
                ('oxapay_sandbox', models.BooleanField(default=True, verbose_name='حالت تست OxaPay')),
                ('invoice_lifetime_minutes', models.PositiveIntegerField(default=60, verbose_name='مهلت پرداخت فاکتور OxaPay / دقیقه')),
                ('oxapay_fee_paid_by_payer', models.BooleanField(default=True, verbose_name='کارمزد OxaPay با پرداخت‌کننده باشد')),
                ('card_to_card_enabled', models.BooleanField(default=False, verbose_name='پرداخت کارت‌به‌کارت فعال باشد')),
                ('card_to_card_text', models.TextField(blank=True, verbose_name='متن کارت‌به‌کارت، فقط وقتی فعال باشد به کاربر نشان داده می‌شود')),
                ('tutorial_text', models.TextField(blank=True, default='آموزش اتصال را از این بخش تنظیم کنید.', verbose_name='متن آموزش اتصال')),
                ('contact_intro_text', models.TextField(blank=True, default='پیام خود را ارسال کنید. پشتیبانی پاسخ شما را بررسی می‌کند.', verbose_name='متن بخش ارتباط با ما')),
                ('after_purchase_text', models.TextField(blank=True, default='اشتراک شما با موفقیت ساخته شد.', verbose_name='متن بعد از خرید موفق')),
                ('is_shop_active', models.BooleanField(default=True, verbose_name='فروشگاه فعال باشد')),
            ],
            options={'verbose_name': 'تنظیمات اصلی ربات', 'verbose_name_plural': 'تنظیمات اصلی ربات'},
        ),
        migrations.CreateModel(
            name='XUIPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('name', models.CharField(max_length=120, verbose_name='نام پنل')),
                ('base_url', models.URLField(verbose_name='آدرس پنل 3x-ui، مثل https://panel.example.com/adminpath')),
                ('api_token', models.CharField(blank=True, max_length=500, verbose_name='API Token پنل 3x-ui')),
                ('verify_ssl', models.BooleanField(default=True, verbose_name='بررسی SSL فعال باشد')),
                ('timeout_seconds', models.PositiveIntegerField(default=20, verbose_name='Timeout API / ثانیه')),
                ('api_base_path', models.CharField(default='/panel/api', max_length=120, verbose_name='مسیر پایه API')),
                ('subscription_base_url', models.URLField(blank=True, verbose_name='آدرس پایه Subscription، اختیاری')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={'verbose_name': 'پنل سنایی / 3x-ui', 'verbose_name_plural': 'پنل‌های سنایی / 3x-ui'},
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('chat_id', models.BigIntegerField(unique=True, verbose_name='Chat ID')),
                ('username', models.CharField(blank=True, max_length=150, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='نام خانوادگی')),
                ('wallet_balance_toman', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18, verbose_name='موجودی کیف پول / تومان')),
                ('state', models.CharField(blank=True, max_length=120, verbose_name='وضعیت موقت ربات')),
                ('temp_data', models.JSONField(blank=True, default=dict, verbose_name='داده موقت')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='مسدود')),
            ],
            options={'verbose_name': 'کاربر تلگرام', 'verbose_name_plural': 'کاربران تلگرام', 'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('name', models.CharField(max_length=120, verbose_name='نام سرویس')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات سرویس')),
                ('inbound_id', models.PositiveIntegerField(verbose_name='شناسه Inbound در پنل 3x-ui')),
                ('inbound_remark', models.CharField(blank=True, max_length=150, verbose_name='نام/Remark اینباند برای یادآوری')),
                ('sort_order', models.PositiveIntegerField(default=10, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('config_link_template', models.TextField(blank=True, help_text='متغیرها: {uuid}, {email}, {inbound_id}, {panel_base_url}, {subscription_base_url}, {service_name}, {plan_name}', verbose_name='قالب لینک کانفیگ، اختیاری')),
                ('subscription_link_template', models.TextField(blank=True, help_text='مثال: https://sub.example.com/sub/{email} یا هر الگویی که در پنل شما استفاده می‌شود.', verbose_name='قالب لینک Subscription، اختیاری')),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.xuipanel', verbose_name='پنل 3x-ui')),
            ],
            options={'verbose_name': 'سرویس', 'verbose_name_plural': 'سرویس‌ها', 'ordering': ['sort_order', 'name']},
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('name', models.CharField(max_length=120, verbose_name='نام اشتراک/پلن')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات پلن')),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت دلاری')),
                ('duration_days', models.PositiveIntegerField(verbose_name='مدت زمان / روز')),
                ('traffic_gb', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='حجم / گیگابایت؛ ۰ یعنی نامحدود')),
                ('user_limit', models.PositiveIntegerField(default=1, verbose_name='تعداد کاربر / IP Limit')),
                ('sort_order', models.PositiveIntegerField(default=10, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='sales.service', verbose_name='سرویس')),
            ],
            options={'verbose_name': 'پلن اشتراک', 'verbose_name_plural': 'پلن‌های اشتراک', 'ordering': ['service__sort_order', 'sort_order', 'price_usd']},
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('source', models.CharField(choices=[('wallet', 'کیف پول'), ('oxapay', 'OxaPay'), ('card', 'کارت‌به‌کارت'), ('admin', 'ثبت دستی مدیر')], default='wallet', max_length=20, verbose_name='روش پرداخت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت/پردازش'), ('paid', 'پرداخت‌شده'), ('provisioned', 'تحویل‌شده'), ('failed', 'ناموفق'), ('expired', 'منقضی'), ('cancelled', 'لغوشده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ دلاری')),
                ('amount_toman', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='مبلغ تومان')),
                ('xui_client_uuid', models.CharField(blank=True, max_length=80, verbose_name='UUID کلاینت')),
                ('xui_client_email', models.CharField(blank=True, max_length=150, verbose_name='Email/شناسه کلاینت در 3x-ui')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('traffic_bytes', models.BigIntegerField(default=0, verbose_name='حجم به بایت؛ ۰ یعنی نامحدود')),
                ('user_limit', models.PositiveIntegerField(default=1, verbose_name='تعداد کاربر')),
                ('config_link', models.TextField(blank=True, verbose_name='لینک کانفیگ')),
                ('subscription_link', models.TextField(blank=True, verbose_name='لینک Subscription')),
                ('qr_image', models.ImageField(blank=True, upload_to='qrcodes/', verbose_name='QR Code')),
                ('admin_note', models.TextField(blank=True, verbose_name='یادداشت مدیر')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.plan', verbose_name='پلن')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.service', verbose_name='سرویس')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='sales.telegramuser', verbose_name='کاربر')),
            ],
            options={'verbose_name': 'سفارش/اشتراک', 'verbose_name_plural': 'سفارش‌ها/اشتراک‌ها', 'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('kind', models.CharField(choices=[('credit', 'افزایش موجودی'), ('debit', 'کاهش موجودی'), ('refund', 'برگشت وجه')], max_length=20, verbose_name='نوع')),
                ('amount_toman', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='مبلغ تومان')),
                ('balance_after_toman', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='موجودی بعد از تراکنش')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='توضیح')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.order', verbose_name='سفارش مرتبط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_transactions', to='sales.telegramuser', verbose_name='کاربر')),
            ],
            options={'verbose_name': 'تراکنش کیف پول', 'verbose_name_plural': 'تراکنش‌های کیف پول', 'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('provider', models.CharField(choices=[('oxapay', 'OxaPay'), ('card', 'کارت‌به‌کارت'), ('admin', 'ثبت دستی مدیر')], default='oxapay', max_length=20, verbose_name='درگاه/روش')),
                ('purpose', models.CharField(choices=[('wallet_topup', 'شارژ کیف پول'), ('direct_order', 'پرداخت مستقیم سفارش')], default='wallet_topup', max_length=30, verbose_name='هدف پرداخت')),
                ('status', models.CharField(choices=[('created', 'ایجاد شده'), ('paying', 'در حال پرداخت'), ('paid', 'پرداخت موفق'), ('failed', 'ناموفق'), ('expired', 'منقضی'), ('cancelled', 'لغوشده')], default='created', max_length=20, verbose_name='وضعیت')),
                ('amount_toman', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='مبلغ تومان')),
                ('amount_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='مبلغ دلاری فاکتور')),
                ('payment_url', models.URLField(blank=True, verbose_name='لینک پرداخت')),
                ('order_id', models.CharField(max_length=80, unique=True, verbose_name='Order ID داخلی برای درگاه')),
                ('track_id', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='Track ID درگاه')),
                ('auto_purchase_after_paid', models.BooleanField(default=False, verbose_name='بعد از پرداخت خودکار خرید انجام شود')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='Payload خام')),
                ('pending_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.plan', verbose_name='پلن قابل خرید بعد از شارژ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='sales.telegramuser', verbose_name='کاربر')),
            ],
            options={'verbose_name': 'پرداخت', 'verbose_name_plural': 'پرداخت‌ها', 'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('message_text', models.TextField(blank=True, verbose_name='متن پیام')),
                ('telegram_message_id', models.BigIntegerField(blank=True, null=True, verbose_name='Message ID')),
                ('is_answered', models.BooleanField(default=False, verbose_name='پاسخ داده شد')),
                ('admin_note', models.TextField(blank=True, verbose_name='یادداشت مدیر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_messages', to='sales.telegramuser', verbose_name='کاربر')),
            ],
            options={'verbose_name': 'پیام پشتیبانی', 'verbose_name_plural': 'پیام‌های پشتیبانی', 'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='CardPaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('amount_toman', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='مبلغ تومان')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('receipt_text', models.TextField(blank=True, verbose_name='متن/شماره پیگیری رسید')),
                ('admin_note', models.TextField(blank=True, verbose_name='یادداشت مدیر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.telegramuser', verbose_name='کاربر')),
            ],
            options={'verbose_name': 'درخواست کارت‌به‌کارت', 'verbose_name_plural': 'درخواست‌های کارت‌به‌کارت', 'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان داخلی')),
                ('text', models.TextField(verbose_name='متن پیام')),
                ('target_chat_id', models.CharField(blank=True, max_length=64, verbose_name='چت آیدی خاص؛ خالی یعنی همه کاربران')),
                ('status', models.CharField(choices=[('draft', 'پیش‌نویس'), ('queued', 'در صف ارسال'), ('sent', 'ارسال شده'), ('failed', 'ناموفق')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='تعداد ارسال موفق')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='تعداد ناموفق')),
                ('last_error', models.TextField(blank=True, verbose_name='آخرین خطا')),
            ],
            options={'verbose_name': 'ارسال پیام گروهی/تکی', 'verbose_name_plural': 'ارسال پیام گروهی/تکی', 'ordering': ['-created_at']},
        ),
    ]
