# Generated by Django 6.0.7 on 2026-08-03 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('client_uuid', models.CharField(max_length=120, verbose_name='شناسه کلاینت / UUID')),
                ('client_email', models.CharField(blank=True, max_length=150, verbose_name='Email/شناسه کلاینت در پنل')),
                ('inbound_id', models.PositiveIntegerField(default=0, verbose_name='شناسه Inbound')),
                ('label', models.CharField(blank=True, max_length=150, verbose_name='نام دلخواه')),
                ('config_link', models.TextField(blank=True, verbose_name='لینک کانفیگ ارسالی کاربر')),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.xuipanel', verbose_name='پنل 3x-ui')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_services', to='sales.telegramuser', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سرویس افزوده\u200cشده کاربر',
                'verbose_name_plural': 'سرویس\u200cهای افزوده\u200cشده کاربران',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'client_uuid'), name='unique_user_linked_client')],
            },
        ),
    ]
