# Generated by Django 6.0.7 on 2026-08-03 15:51

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_linkedservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpaymentrequest',
            name='auto_approved',
            field=models.BooleanField(default=False, verbose_name='تایید خودکار با پیامک'),
        ),
        migrations.AddField(
            model_name='cardpaymentrequest',
            name='base_amount_toman',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18, verbose_name='مبلغ درخواستی اولیه / تومان'),
        ),
        migrations.AddField(
            model_name='cardpaymentrequest',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='انقضای فاکتور'),
        ),
        migrations.AddField(
            model_name='cardpaymentrequest',
            name='receipt_file_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='شناسه تصویر رسید در تلگرام'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='card_auto_confirm_enabled',
            field=models.BooleanField(default=False, verbose_name='تایید خودکار کارت\u200cبه\u200cکارت با پیامک بانکی'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='card_invoice_minutes',
            field=models.PositiveIntegerField(default=30, verbose_name='مهلت پرداخت کارت\u200cبه\u200cکارت / دقیقه'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='sms_allowed_senders',
            field=models.CharField(blank=True, help_text='با کاما جدا کنید، مثل: 200080,7575,9830000. خالی یعنی هر فرستنده\u200cای پذیرفته می\u200cشود.', max_length=500, verbose_name='شماره\u200cهای مجاز بانک'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='sms_webhook_secret',
            field=models.CharField(blank=True, help_text='در آدرس وبهوک اپ پیامک\u200cفرست قرار می\u200cگیرد. خالی بگذارید تا خودکار ساخته شود.', max_length=120, verbose_name='کلید مخفی وبهوک پیامک'),
        ),
        migrations.AlterField(
            model_name='cardpaymentrequest',
            name='amount_toman',
            field=models.DecimalField(decimal_places=0, max_digits=18, verbose_name='مبلغ دقیق واریز / تومان'),
        ),
        migrations.CreateModel(
            name='BankSms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('sender', models.CharField(blank=True, max_length=64, verbose_name='شماره فرستنده')),
                ('raw_text', models.TextField(verbose_name='متن پیامک')),
                ('parsed_amount_toman', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True, verbose_name='مبلغ استخراج\u200cشده / تومان')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='نتیجه بررسی')),
                ('matched_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_messages', to='sales.cardpaymentrequest', verbose_name='درخواست منطبق')),
            ],
            options={
                'verbose_name': 'پیامک بانکی',
                'verbose_name_plural': 'پیامک\u200cهای بانکی',
                'ordering': ['-created_at'],
            },
        ),
    ]
