# Generated by Django 6.0.7 on 2026-08-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_cardpaymentrequest_auto_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpaymentrequest',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان اطلاع\u200cرسانی به کاربر'),
        ),
    ]
