# Generated by Django 6.0.7 on 2026-08-03 16:16

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_cardpaymentrequest_notified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpaymentrequest',
            name='auto_purchase_after_paid',
            field=models.BooleanField(default=False, verbose_name='بعد از تایید، سرویس خودکار ساخته شود'),
        ),
        migrations.AddField(
            model_name='cardpaymentrequest',
            name='created_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_requests', to='sales.order', verbose_name='سفارش ساخته\u200cشده'),
        ),
        migrations.AddField(
            model_name='cardpaymentrequest',
            name='pending_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.plan', verbose_name='پلن در انتظار خرید'),
        ),
        migrations.AddField(
            model_name='plan',
            name='price_toman',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18, verbose_name='قیمت تومانی، برای کارت\u200cبه\u200cکارت و کیف پول'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='card_bank_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='نام بانک'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='card_holder_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='نام صاحب کارت'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='card_number',
            field=models.CharField(blank=True, help_text='۱۶ رقم، با یا بدون فاصله. به کاربر به صورت قابل کپی نمایش داده می\u200cشود.', max_length=32, verbose_name='شماره کارت'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت دلاری، برای پرداخت کریپتو'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='card_to_card_text',
            field=models.TextField(blank=True, verbose_name='توضیح اضافه کارت\u200cبه\u200cکارت، اختیاری'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='dollar_rate_toman',
            field=models.DecimalField(decimal_places=0, default=Decimal('60000'), max_digits=18, verbose_name='نرخ دلار به تومان، برای شارژ کیف پول و نمایش تخفیف'),
        ),
    ]
