# Generated by Django 6.0 on 2026-08-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_fill_plan_price_toman'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('question', models.CharField(help_text='روی دکمه نمایش داده می\u200cشود، پس کوتاه بنویسید. حداکثر ۱۰۰ کاراکتر.', max_length=100, verbose_name='سوال')),
                ('answer', models.TextField(help_text='می\u200cتوانید از تگ\u200cهای <b> و <code> و لینک استفاده کنید.', verbose_name='پاسخ')),
                ('sort_order', models.PositiveIntegerField(default=10, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'سوال متداول',
                'verbose_name_plural': 'سوالات متداول',
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='faq_intro_text',
            field=models.TextField(blank=True, default='سوال خود را از لیست زیر انتخاب کنید تا پاسخ آن را ببینید.', verbose_name='متن بالای بخش سوالات متداول'),
        ),
    ]
