# Generated by Django 6.0 on 2026-08-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_faqitem_sitesetting_faq_intro_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='force_https',
            field=models.BooleanField(default=True, help_text='اگر روی دامنه گواهی SSL دارید روشن بماند.', verbose_name='آدرس\u200cها با https ساخته شوند'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='public_domain',
            field=models.CharField(blank=True, help_text='فقط دامنه، بدون https:// و بدون اسلش. مثل shop.example.com', max_length=255, verbose_name='دامنه پنل و ربات'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='ssl_cert_path',
            field=models.CharField(blank=True, help_text='مثل /etc/letsencrypt/live/shop.example.com/fullchain.pem', max_length=500, verbose_name='مسیر فایل گواهی SSL'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='ssl_key_path',
            field=models.CharField(blank=True, help_text='مثل /etc/letsencrypt/live/shop.example.com/privkey.pem', max_length=500, verbose_name='مسیر فایل کلید خصوصی SSL'),
        ),
    ]
