# Generated by Django 6.0 on 2026-08-04 17:50

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_sitesetting_force_https_sitesetting_public_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpaymentrequest',
            name='discount_toman',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18, verbose_name='تخفیف اعمال\u200cشده / تومان'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_toman',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18, verbose_name='تخفیف اعمال\u200cشده / تومان'),
        ),
        migrations.AddField(
            model_name='payment',
            name='discount_toman',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18, verbose_name='تخفیف اعمال\u200cشده / تومان'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='daily_report_enabled',
            field=models.BooleanField(default=False, help_text='گزارش روزانه و گزارش ماهانه به «چت آیدی مدیر» فرستاده می\u200cشود.', verbose_name='ارسال گزارش فروش به مدیر'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='daily_report_hour',
            field=models.PositiveSmallIntegerField(default=23, help_text='عدد ۰ تا ۲۳ به وقت سرور. گزارش ماهانه هم در همین ساعتِ روز اول ماه فرستاده می\u200cشود.', verbose_name='ساعت ارسال گزارش روزانه'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='telegram_use_webhook',
            field=models.BooleanField(default=False, help_text='فقط وقتی روشن کنید که دامنه و SSL تنظیم شده باشد. بعد از روشن کردن، روی سرور «vpnshop webhook» را بزنید.', verbose_name='دریافت پیام\u200cها با Webhook به\u200cجای Polling'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='telegram_webhook_secret',
            field=models.CharField(blank=True, help_text='خالی بگذارید تا خودکار ساخته شود. در آدرس وبهوک و هدر امنیتی تلگرام استفاده می\u200cشود.', max_length=120, verbose_name='کلید مخفی وبهوک تلگرام'),
        ),
        migrations.AddField(
            model_name='xuipanel',
            name='openapi_add_client_path',
            field=models.CharField(blank=True, max_length=200, verbose_name='مسیر ساخت کلاینت در این پنل'),
        ),
        migrations.AddField(
            model_name='xuipanel',
            name='openapi_fetched_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان خواندن ساختار API'),
        ),
        migrations.AddField(
            model_name='xuipanel',
            name='openapi_note',
            field=models.CharField(blank=True, max_length=300, verbose_name='نتیجه آخرین خواندن ساختار API'),
        ),
        migrations.AddField(
            model_name='xuipanel',
            name='openapi_schema',
            field=models.JSONField(blank=True, default=dict, verbose_name='ساختار API خوانده\u200cشده از پنل'),
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('code', models.CharField(help_text='حروف انگلیسی و عدد. بدون فاصله. مثل NOWRUZ40', max_length=40, unique=True, verbose_name='کد تخفیف')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='عنوان داخلی')),
                ('kind', models.CharField(choices=[('percent', 'درصدی'), ('fixed', 'مبلغ ثابت تومانی')], default='percent', max_length=20, verbose_name='نوع تخفیف')),
                ('percent', models.PositiveSmallIntegerField(default=0, help_text='برای نوع درصدی. عدد ۱ تا ۱۰۰.', verbose_name='درصد تخفیف')),
                ('amount_toman', models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='برای نوع مبلغ ثابت.', max_digits=18, verbose_name='مبلغ تخفیف / تومان')),
                ('max_discount_toman', models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='برای تخفیف درصدی. ۰ یعنی بدون سقف.', max_digits=18, verbose_name='سقف تخفیف / تومان')),
                ('min_order_toman', models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='۰ یعنی محدودیتی ندارد.', max_digits=18, verbose_name='حداقل مبلغ خرید / تومان')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='شروع اعتبار')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='پایان اعتبار')),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='۰ یعنی نامحدود.', verbose_name='حداکثر دفعات استفاده در کل')),
                ('max_uses_per_user', models.PositiveIntegerField(default=1, help_text='۰ یعنی نامحدود.', verbose_name='حداکثر دفعات برای هر کاربر')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='تعداد استفاده\u200cشده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('note', models.TextField(blank=True, verbose_name='یادداشت مدیر')),
                ('plans', models.ManyToManyField(blank=True, help_text='خالی یعنی برای همه پلن\u200cها.', to='sales.plan', verbose_name='فقط برای این پلن\u200cها')),
                ('services', models.ManyToManyField(blank=True, help_text='خالی یعنی برای همه سرویس\u200cها.', to='sales.service', verbose_name='فقط برای این سرویس\u200cها')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کدهای تخفیف',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='cardpaymentrequest',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_requests', to='sales.discountcode', verbose_name='کد تخفیف'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='sales.discountcode', verbose_name='کد تخفیف'),
        ),
        migrations.AddField(
            model_name='payment',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='sales.discountcode', verbose_name='کد تخفیف'),
        ),
        migrations.CreateModel(
            name='DiscountRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('amount_toman', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18, verbose_name='مبلغ تخفیف / تومان')),
                ('amount_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='مبلغ تخفیف / دلار')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='sales.discountcode', verbose_name='کد تخفیف')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_redemptions', to='sales.order', verbose_name='سفارش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_redemptions', to='sales.telegramuser', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'استفاده از کد تخفیف',
                'verbose_name_plural': 'استفاده\u200cهای کد تخفیف',
                'ordering': ['-created_at'],
            },
        ),
    ]
