# Generated by Django 6.0 on 2026-08-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_cardpaymentrequest_discount_toman_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('queued', 'در صف ارسال'), ('sending', 'در حال ارسال'), ('sent', 'ارسال شده'), ('failed', 'ناموفق')], default='draft', max_length=20, verbose_name='وضعیت'),
        ),
    ]
