# Generated by Django 6.0 on 2026-08-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_alter_broadcast_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال'),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='answered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال پاسخ'),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='reply_error',
            field=models.CharField(blank=True, max_length=300, verbose_name='نتیجه ارسال پاسخ'),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='reply_text',
            field=models.TextField(blank=True, help_text='بنویسید و ذخیره کنید. پاسخ همان لحظه در تلگرام برای کاربر فرستاده می\u200cشود.', verbose_name='پاسخ شما به کاربر'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='target_chat_id',
            field=models.CharField(blank=True, help_text='خالی بگذارید تا برای همه کاربران ربات ارسال شود. برای ارسال به یک نفر، Chat ID او را بنویسید.', max_length=64, verbose_name='گیرنده'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='text',
            field=models.TextField(help_text='می\u200cتوانید از تگ\u200cهای <b> و <code> و لینک استفاده کنید.', verbose_name='متن پیام'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='title',
            field=models.CharField(blank=True, max_length=150, verbose_name='نام این پیام در فهرست'),
        ),
    ]
