# Generated by Django 6.0 on 2026-08-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_broadcast_sent_at_supportmessage_answered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpaymentrequest',
            name='client_name',
            field=models.CharField(blank=True, max_length=64, verbose_name='نام کاربری انتخاب\u200cشده برای کانفیگ'),
        ),
        migrations.AddField(
            model_name='payment',
            name='client_name',
            field=models.CharField(blank=True, max_length=64, verbose_name='نام کاربری انتخاب\u200cشده برای کانفیگ'),
        ),
    ]
