# Generated by Django 6.0 on 2026-08-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_cardpaymentrequest_client_name_payment_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='traffic_ended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان تمام شدن حجم'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='service_grace_days',
            field=models.PositiveSmallIntegerField(default=30, help_text='بعد از تمام شدن زمان یا حجم یک اشتراک، این تعداد روز هنوز در «سرویس\u200cهای من» کاربر دیده می\u200cشود تا بتواند تمدیدش کند، بعد از آن از فهرست او حذف می\u200cشود. سفارش در پنل و گزارش\u200cها باقی می\u200cماند. ۰ یعنی بلافاصله حذف شود.', verbose_name='روزهای نمایش سرویس بعد از اتمام'),
        ),
    ]
