# Generated by Django 6.0 on 2026-08-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_order_traffic_ended_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='panel_https_port',
            field=models.PositiveIntegerField(default=443, help_text='اگر پورت ۴۴۳ و ۸۰ را برای x-ui می\u200cخواهید، اینجا ۸۴۴۳ بگذارید تا پنل با آن\u200cها تداخل نکند. تلگرام فقط پورت\u200cهای ۴۴۳، ۸۰، ۸۸ و ۸۴۴۳ را برای Webhook قبول می\u200cکند. بعد از تغییر، روی سرور «vpnshop domain» را بزنید.', verbose_name='پورت پنل روی اینترنت'),
        ),
    ]
