# Generated by Django 6.0 on 2026-08-10 12:00

from django.db import migrations, models


def carry_inbound_forward(apps, schema_editor):
    """Move each service's single inbound into the new comma-separated list.

    Runs while both columns exist, so an install that already sells services
    keeps working across the upgrade instead of losing which inbound they use.
    """
    Service = apps.get_model('sales', 'Service')
    for service in Service.objects.all().iterator():
        service.inbound_ids = str(service.inbound_id or '').strip()
        service.save(update_fields=['inbound_ids'])


def carry_inbound_back(apps, schema_editor):
    Service = apps.get_model('sales', 'Service')
    for service in Service.objects.all().iterator():
        first = str(service.inbound_ids or '').split(',')[0].strip()
        service.inbound_id = int(first) if first.isdigit() else 0
        service.save(update_fields=['inbound_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_sitesetting_panel_https_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='inbound_ids',
            field=models.CharField(default='', help_text='یک یا چند شناسه، با کاما جدا شده. مثل: 1,3,5', max_length=200, verbose_name='شناسه\u200cهای Inbound در پنل 3x-ui'),
        ),
        migrations.RunPython(carry_inbound_forward, carry_inbound_back),
        migrations.RemoveField(
            model_name='service',
            name='inbound_id',
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='welcome_text',
            field=models.TextField(blank=True, default='سلام {name} 🌿\nبه <b>{shop}</b> خوش آمدید.\n\nبرای شروع، از دکمه\u200cهای پایین یکی را انتخاب کنید. 👇', help_text='می\u200cتوانید ایموجی بگذارید. متغیرها: {name} نام کاربر، {shop} نام فروشگاه، {username} یوزرنیم تلگرام، {balance} موجودی کیف پول. تگ\u200cهای &lt;b&gt; و &lt;i&gt; و &lt;code&gt; هم کار می\u200cکنند.', verbose_name='پیام خوش\u200cآمدگویی ربات'),
        ),
        migrations.AddField(
            model_name='xuipanel',
            name='inbounds_cache',
            field=models.JSONField(blank=True, default=list, verbose_name='اینباندهای خوانده\u200cشده از پنل'),
        ),
        migrations.AddField(
            model_name='xuipanel',
            name='inbounds_fetched_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان خواندن اینباندها'),
        ),
        migrations.AddField(
            model_name='xuipanel',
            name='sub_detected',
            field=models.JSONField(blank=True, default=dict, verbose_name='تنظیمات Subscription خوانده\u200cشده از پنل'),
        ),
        migrations.AddField(
            model_name='xuipanel',
            name='sub_domain',
            field=models.CharField(blank=True, help_text='خالی یعنی همان دامنه\u200cی آدرس پنل استفاده شود.', max_length=255, verbose_name='دامنه Subscription'),
        ),
        migrations.AddField(
            model_name='xuipanel',
            name='sub_mode',
            field=models.CharField(choices=[('auto', 'خودکار از روی تنظیمات خود پنل'), ('manual', 'دستی، با مقادیر زیر'), ('off', 'لینک Subscription داده نشود')], default='auto', help_text='خودکار یعنی از «تنظیمات ← Subscription» همین پنل خوانده شود.', max_length=10, verbose_name='روش ساخت لینک Subscription'),
        ),
        migrations.AddField(
            model_name='xuipanel',
            name='sub_note',
            field=models.CharField(blank=True, max_length=300, verbose_name='نتیجه آخرین خواندن تنظیمات Subscription'),
        ),
        migrations.AddField(
            model_name='xuipanel',
            name='sub_path',
            field=models.CharField(default='/sub/', help_text='با اسلش شروع و تمام شود. مثل /sub/', max_length=120, verbose_name='مسیر Subscription'),
        ),
        migrations.AddField(
            model_name='xuipanel',
            name='sub_port',
            field=models.PositiveIntegerField(default=2096, help_text='پورتی که در تنظیمات Subscription پنل انتخاب کرده\u200cاید. پیش\u200cفرض 3x-ui معمولا 2096 یا 10882 است.', verbose_name='پورت Subscription'),
        ),
        migrations.AddField(
            model_name='xuipanel',
            name='sub_scheme',
            field=models.CharField(choices=[('https', 'https'), ('http', 'http')], default='https', max_length=5, verbose_name='پروتکل Subscription'),
        ),
    ]
