# Generated by Django 6.0 on 2026-08-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_multi_inbound_and_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='xui_sub_id',
            field=models.CharField(blank=True, max_length=150, verbose_name='Subscription ID در پنل'),
        ),
        migrations.AlterField(
            model_name='service',
            name='config_link_template',
            field=models.TextField(blank=True, help_text='خالی بگذارید؛ لینک مستقیماً از خود پنل گرفته می\u200cشود. متغیرها: {uuid}, {email}, {sub_id}, {inbound_id}, {inbound_ids}, {panel_base_url}, {subscription_base_url}, {service_name}, {plan_name}', verbose_name='قالب لینک کانفیگ، اختیاری'),
        ),
        migrations.AlterField(
            model_name='service',
            name='subscription_link_template',
            field=models.TextField(blank=True, help_text='خالی بگذارید؛ خودکار از تنظیمات Subscription پنل ساخته می\u200cشود. اگر پر می\u200cکنید، از {sub_id} استفاده کنید نه {email}: لینک Subscription در 3x-ui با «Subscription ID» کلاینت ساخته می\u200cشود. مثال: https://sub.example.com:2096/sub/{sub_id}', verbose_name='قالب لینک Subscription، اختیاری'),
        ),
    ]
