# Generated by Django 6.0 on 2026-09-04 12:44

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_order_sub_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_label',
            field=models.CharField(blank=True, help_text='نامی که همکار برای مشتری نهایی وارد کرده. در Comment کانفیگ پنل هم ثبت می\u200cشود.', max_length=120, verbose_name='نام مشتری همکار'),
        ),
        migrations.AddField(
            model_name='order',
            name='partner_base_toman',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18, verbose_name='قیمت عادی در لحظه فروش / تومان'),
        ),
        migrations.AddField(
            model_name='order',
            name='revenue_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='زمان شناسایی درآمد'),
        ),
        migrations.AddField(
            model_name='order',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان غیرفعال\u200cسازی بابت بدهی'),
        ),
        migrations.AddField(
            model_name='plan',
            name='partner_price_toman',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='۰ یعنی تعریف نشده؛ در آن صورت همکاران قیمت عادی این پلن را می\u200cبینند.', max_digits=18, verbose_name='قیمت همکاری / تومان'),
        ),
        migrations.AddField(
            model_name='plan',
            name='partner_price_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='۰ یعنی از روی قیمت تومانی و نرخ دلار سایت حساب شود.', max_digits=10, verbose_name='قیمت همکاری / دلار'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='partner_default_cycle_days',
            field=models.PositiveSmallIntegerField(default=7, help_text='برای همکار تازه\u200cای که از روی درخواست ساخته می\u200cشود. بعداً برای هر همکار جداگانه قابل تغییر است.', verbose_name='مهلت پرداخت پیش\u200cفرض همکار / روز'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='partner_delete_refund_hours',
            field=models.PositiveSmallIntegerField(default=24, help_text='اگر همکار کانفیگی را در این مهلت حذف کند و فاکتورش هنوز پرداخت نشده باشد، مبلغ از فاکتور برداشته می\u200cشود. ۰ یعنی هیچ برگشتی انجام نشود.', verbose_name='مهلت برگشت وجه بعد از حذف کانفیگ / ساعت'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='partner_invoice_warn_hours',
            field=models.PositiveSmallIntegerField(default=24, help_text='این هشدار برای هر فاکتور فقط یک بار ارسال می\u200cشود.', verbose_name='ارسال هشدار چند ساعت قبل از سررسید فاکتور'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='partner_panel_welcome_text',
            field=models.TextField(blank=True, default='به پنل همکاری خوش آمدید.', verbose_name='متن بالای پنل همکار'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='partner_program_enabled',
            field=models.BooleanField(default=False, help_text='تا وقتی خاموش است، دستور /work برای همه پیام «این بخش فعال نیست» می\u200cدهد.', verbose_name='سیستم همکاری در فروش فعال باشد'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='partner_request_enabled',
            field=models.BooleanField(default=True, help_text='خاموش کردن این گزینه فقط جلوی درخواست تازه را می\u200cگیرد؛ همکاران فعلی دست\u200cنخورده می\u200cمانند.', verbose_name='ثبت درخواست همکاری باز باشد'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='partner_request_intro_text',
            field=models.TextField(blank=True, default='برای همکاری در فروش، اطلاعات زیر را ارسال کنید تا بررسی شود.', verbose_name='متن معرفی همکاری برای کاربر عادی'),
        ),
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('wallet', 'کیف پول'), ('oxapay', 'OxaPay'), ('card', 'کارت\u200cبه\u200cکارت'), ('admin', 'ثبت دستی مدیر'), ('partner_credit', 'اعتباری همکار')], default='wallet', max_length=20, verbose_name='روش پرداخت'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='purpose',
            field=models.CharField(choices=[('wallet_topup', 'شارژ کیف پول'), ('direct_order', 'پرداخت مستقیم سفارش'), ('partner_invoice', 'پرداخت فاکتور همکاری')], default='wallet_topup', max_length=30, verbose_name='هدف پرداخت'),
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('display_name', models.CharField(help_text='همین نام در Comment کانفیگ\u200cهای 3x-ui ثبت می\u200cشود، پس انگلیسی و کوتاه بهتر است.', max_length=120, verbose_name='نام همکار')),
                ('is_active', models.BooleanField(default=True, help_text='غیرفعال کردن، دسترسی به پنل همکار را می\u200cبندد ولی فاکتورها و کانفیگ\u200cهای موجود را دست نمی\u200cزند.', verbose_name='فعال')),
                ('billing_mode', models.CharField(choices=[('prepaid', 'پرداخت فوری'), ('credit', 'اعتباری، تسویه دوره\u200cای')], default='prepaid', max_length=20, verbose_name='نوع همکاری')),
                ('billing_cycle_days', models.PositiveSmallIntegerField(default=7, help_text='دوره از اولین سفارش شروع می\u200cشود، نه از اول ماه. فقط برای همکاری اعتباری معنی دارد.', verbose_name='مهلت پرداخت / روز')),
                ('credit_limit_toman', models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='۰ یعنی نامحدود. سفارشی که باعث عبور از این سقف شود، رد می\u200cشود.', max_digits=18, verbose_name='سقف اعتبار / تومان')),
                ('discount_percent', models.PositiveSmallIntegerField(default=0, help_text='روی قیمت همکاری اعمال می\u200cشود، نه روی قیمت عادی. مثال: قیمت همکاری ۳۵۰٬۰۰۰ با ۱۰٪ می\u200cشود ۳۱۵٬۰۰۰.', verbose_name='درصد تخفیف همکار')),
                ('note', models.TextField(blank=True, verbose_name='یادداشت مدیر')),
                ('allowed_plans', models.ManyToManyField(blank=True, help_text='برای استثنای پلنی. اگر پر باشد بر «سرویس\u200cهای مجاز» مقدم است.', related_name='partners', to='sales.plan', verbose_name='پلن\u200cهای مجاز')),
                ('allowed_services', models.ManyToManyField(blank=True, help_text='خالی بگذارید تا همه سرویس\u200cها مجاز باشند.', related_name='partners', to='sales.service', verbose_name='سرویس\u200cهای مجاز')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner', to='sales.telegramuser', verbose_name='حساب تلگرام')),
            ],
            options={
                'verbose_name': 'همکار فروش',
                'verbose_name_plural': 'همکاران فروش',
                'ordering': ['display_name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='sales.partner', verbose_name='همکار فروشنده'),
        ),
        migrations.CreateModel(
            name='PartnerInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('number', models.CharField(blank=True, max_length=32, unique=True, verbose_name='شماره فاکتور')),
                ('status', models.CharField(choices=[('open', 'باز، در جریان'), ('overdue', 'سررسید گذشته'), ('paid', 'پرداخت\u200cشده'), ('cancelled', 'لغوشده')], default='open', max_length=20, verbose_name='وضعیت')),
                ('opened_at', models.DateTimeField(verbose_name='شروع دوره')),
                ('due_at', models.DateTimeField(verbose_name='سررسید')),
                ('total_toman', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18, verbose_name='جمع فاکتور / تومان')),
                ('total_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='جمع فاکتور / دلار')),
                ('warned_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال هشدار سررسید')),
                ('suspended_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان غیرفعال\u200cسازی کانفیگ\u200cها')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پرداخت')),
                ('settled_by', models.CharField(blank=True, choices=[('wallet', 'کیف پول'), ('card', 'کارت\u200cبه\u200cکارت'), ('oxapay', 'OxaPay'), ('admin', 'تسویه دستی مدیر')], max_length=20, verbose_name='تسویه از راه')),
                ('admin_note', models.TextField(blank=True, verbose_name='یادداشت مدیر')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='sales.partner', verbose_name='همکار')),
            ],
            options={
                'verbose_name': 'فاکتور همکاری',
                'verbose_name_plural': 'فاکتورهای همکاری',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.AddField(
            model_name='cardpaymentrequest',
            name='partner_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_requests', to='sales.partnerinvoice', verbose_name='فاکتور همکاری'),
        ),
        migrations.AddField(
            model_name='order',
            name='suspended_by_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspended_orders', to='sales.partnerinvoice', verbose_name='غیرفعال\u200cشده بابت فاکتور'),
        ),
        migrations.AddField(
            model_name='payment',
            name='partner_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='sales.partnerinvoice', verbose_name='فاکتور همکاری'),
        ),
        migrations.CreateModel(
            name='PartnerInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('kind', models.CharField(choices=[('new', 'سفارش جدید'), ('renew', 'تمدید'), ('adjust', 'اصلاح دستی')], default='new', max_length=20, verbose_name='نوع')),
                ('title', models.CharField(max_length=200, verbose_name='شرح')),
                ('amount_toman', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='مبلغ / تومان')),
                ('amount_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='مبلغ / دلار')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='لغوشده')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان لغو')),
                ('cancel_reason', models.CharField(blank=True, max_length=200, verbose_name='دلیل لغو')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.partnerinvoice', verbose_name='فاکتور')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_invoice_items', to='sales.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'ردیف فاکتور همکاری',
                'verbose_name_plural': 'ردیف\u200cهای فاکتور همکاری',
                'ordering': ['invoice', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerPlanPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('price_toman', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=18, verbose_name='قیمت اختصاصی / تومان')),
                ('price_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='۰ یعنی از روی قیمت تومانی و نرخ دلار سایت حساب شود.', max_digits=10, verbose_name='قیمت اختصاصی / دلار')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_prices', to='sales.partner', verbose_name='همکار')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_prices', to='sales.plan', verbose_name='پلن')),
            ],
            options={
                'verbose_name': 'قیمت اختصاصی همکار',
                'verbose_name_plural': 'قیمت\u200cهای اختصاصی همکاران',
                'ordering': ['partner__display_name', 'plan__service__sort_order', 'plan__sort_order'],
            },
        ),
        migrations.CreateModel(
            name='PartnerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('full_name', models.CharField(max_length=120, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='شماره تماس')),
                ('sales_channel', models.CharField(blank=True, max_length=200, verbose_name='کانال یا محل فروش')),
                ('monthly_volume', models.CharField(blank=True, max_length=100, verbose_name='حدود فروش ماهانه')),
                ('note', models.TextField(blank=True, verbose_name='توضیح متقاضی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان بررسی')),
                ('admin_note', models.TextField(blank=True, verbose_name='یادداشت مدیر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_requests', to='sales.telegramuser', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'درخواست همکاری',
                'verbose_name_plural': 'درخواست\u200cهای همکاری',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='partnerinvoice',
            index=models.Index(fields=['status', 'due_at'], name='sales_partn_status_c36842_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerinvoice',
            index=models.Index(fields=['partner', 'status'], name='sales_partn_partner_3af711_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='partnerplanprice',
            unique_together={('partner', 'plan')},
        ),
    ]
